# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.RemoveField(
            model_name='reportbyproject',
            name='submit_date',
        ),
        migrations.AddField(
            model_name='reportbyproject',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Submit date'),
        ),
        migrations.AlterField(
            model_name='reportbyproject',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Opening date'),
        ),
    ]
