# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0002_auto_20160926_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_builder.ReportByProject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_builder.Report'),
        ),
    ]
