# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0002_auto_20180629_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportbyproject',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='reportbyproject',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Opening date'),
        ),
    ]
