# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0002_city_country'),
        ('report_builder', '0003_auto_20161007_1653'),
    ]

    operations = [
    ]
