# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0004_merge_20161007_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('template_admin', 'Can create and edit report templates'),), 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
    ]
